### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by ben314159** [ShoulM/Primo-App-Store#5]
Hi,

I'm currently unable to get Primo Studio to run due to getting a certificate error - see the following output:

```
$ gulp run --view TEST --ve
[11:36:10] Using gulpfile ~/Primo-Studio/gulpfile.js
[11:36:10] Starting 'connect:primo_explore'...
[11:36:10] Finished 'connect:primo_explore' after 22 ms
[11:36:10] Starting 'reinstall-primo-node-modules'...
[11:36:10] Finished 'reinstall-primo-node-modules' after 41 μs
[11:36:10] Starting 'custom-html-templates'...
[11:36:10] Starting 'custom-scss'...
[11:36:10] Finished 'custom-scss' after 89 μs
[11:36:10] Starting 'custom-css'...
[11:36:10] Finished 'custom-html-templates' after 16 ms
[11:36:10] Starting 'custom-js'...
[11:36:10] Finished 'custom-js' after 4.19 ms
[11:36:10] Finished 'custom-css' after 17 ms
[11:36:10] Starting 'run'...
[11:36:10] Finished 'run' after 22 μs
[Browsersync] Access URLs:
 ----------------------------------
       Local: http://localhost:8003
    External: http://10.0.2.15:8003
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.2.15:3001
 ----------------------------------
[Browsersync] Serving files from: primo-explore
undefined
undefined
vid=TEST
vid=TEST
url=undefined
this is the current path: /primo-explore/search
fixedurl:https://wlv.primo.exlibrisgroup.com:443/primo-explore/search?vid=TEST
port:443
hostname:wlv.primo.exlibrisgroup.com
req.url :/primo-explore/search?vid=TEST
{ host: 'localhost:8003',
  'user-agent':
   'Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0',
  accept:
   'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'accept-language': 'en-US,en;q=0.5',
  'accept-encoding': 'identity',
  cookie: 'lang=en-US',
  connection: 'keep-alive',
  'upgrade-insecure-requests': '1',
  dnt: '1',
  'X-From-ExL-API-Gateway': '1',
  'Accept-Encoding': '' }
method is https
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: localhost. is not in the cert's altnames: DNS:*.primo.exlibrisgroup.com, DNS:primo.exlibrisgroup.com
    at Object.checkServerIdentity (tls.js:229:17)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1065:27)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:635:8)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

The error occurs when attempting to browse ``localhost:8003/discovery/?vid=TEST``
I have also tried using the ip address of the computer instead of localhost.

I have tried this on two completely separate systems, satisfying all the installation requirements, and get the same error. The  proxy server variable is set in ``gulp/config.js``

```
 var PROXY_SERVER = 'https://wlv.primo.exlibrisgroup.com:443';
```

Do you have any suggestions please? Am I doing something wrong, or have I missed something obvious?

I'm using the latest commit of Primo Studio from the master branch.

Thanks

**Comment by gilax** [comment]
Hi,

Primo Studio is a web-based application enabling one-click activation for addons, there is no need to install it locally.

Next week we’ll be hosting spotlight session focusing on Primo Studio. We hope you can [register for one of the two sessions](http://bit.ly/UpdateWebinars-Primo) below to see a live demo and learn more about this collaborative customization tool. It’ll expand your knowledge beyond the highlights presented in our [Primo Studio introductory video](http://bit.ly/ExLibris-PrimoStudio):  

•	June 13 – 7:00 am (London), 9:00 am (Tel Aviv), 4:00 pm (Sydney)
•	June 13 – 8:00 am (San Francisco), 11:00 am (New York), 4:00 pm (London), 6:00 pm (Tel Aviv)
